apiVersion: v1
kind: Pod
metadata:
  name: kube-apiserver
  namespace: kube-system
  labels:
    component: kube-apiserver
    tier: control-plane
spec:
  containers:
  - name: kube-apiserver
    image: registry.k8s.io/kube-apiserver:v1.30.0
    command:
    - kube-apiserver
    args:
    - --etcd-servers=http://HOST_IP:2379
    - --service-cluster-ip-range=10.0.0.0/24
    - --bind-address=0.0.0.0
    - --secure-port=6443
    - --advertise-address=HOST_IP
    - --authorization-mode=AlwaysAllow
    - --token-auth-file=/etc/kubernetes/pki/token.csv
    - --enable-priority-and-fairness=false
    - --allow-privileged=true
    - --profiling=false
    - --storage-backend=etcd3
    - --storage-media-type=application/json
    - --v=0
    -
    - --service-account-issuer=https://kubernetes.default.svc.cluster.local
    - --service-account-key-file=/etc/kubernetes/pki/sa.pub
    - --service-account-signing-key-file=/etc/kubernetes/pki/sa.key
    ports:
    - containerPort: 6443
      name: https
      protocol: TCP
    volumeMounts:
    - name: k8s-certs
      mountPath: /etc/kubernetes/pki
      readOnly: true
    resources:
      requests:
        cpu: 250m
        memory: 256Mi
      limits:
        cpu: 1000m
        memory: 1Gi
  volumes:
  - name: k8s-certs
    hostPath:
      path: /etc/kubernetes/pki
      type: DirectoryOrCreate
  hostNetwork: true
  restartPolicy: Always
