apiVersion: v1
kind: Pod
metadata:
  name: debug-profiler
  labels:
    app: debug-profiler
    purpose: profiling
spec:
  # Privileged mode is required to access host processes and run perf
  hostPID: true
  hostNetwork: true
  
  containers:
  - name: profiler
    image: verizondigital/kubectl-flame:v0.2.4-perf
    command:
    - sleep
    - infinity
    
    # Security context for privileged access
    securityContext:
      privileged: true
      capabilities:
        add:
        - SYS_ADMIN
        - SYS_PTRACE
    
    # Resource limits
    resources:
      requests:
        memory: "256Mi"
        cpu: "100m"
      limits:
        memory: "512Mi"
        cpu: "500m"
    
    # Mount host directories for profiling
    volumeMounts:
    - name: sys
      mountPath: /sys
      readOnly: true
    - name: debugfs
      mountPath: /sys/kernel/debug
    - name: results
      mountPath: /results
  
  volumes:
  - name: sys
    hostPath:
      path: /sys
      type: Directory
  - name: debugfs
    hostPath:
      path: /sys/kernel/debug
      type: Directory
  - name: results
    hostPath:
      path: /tmp/profiling-results
      type: DirectoryOrCreate
  
  restartPolicy: Never

