apiVersion: v1
kind: Pod
metadata:
  name: etcd
  namespace: kube-system
  labels:
    component: etcd
    tier: control-plane
spec:
  containers:
  - name: etcd
    image: registry.k8s.io/etcd:3.5.10-0
    command:
    - etcd
    - --advertise-client-urls=http://HOST_IP:2379
    - --listen-client-urls=http://0.0.0.0:2379
    - --data-dir=/var/lib/etcd
    - --listen-peer-urls=http://0.0.0.0:2380
    - --initial-cluster=default=http://HOST_IP:2380
    - --initial-advertise-peer-urls=http://HOST_IP:2380
    - --initial-cluster-state=new
    - --initial-cluster-token=test-token
    ports:
    - containerPort: 2379
      name: client
      protocol: TCP
    - containerPort: 2380
      name: peer
      protocol: TCP
    volumeMounts:
    - name: etcd-data
      mountPath: /var/lib/etcd
    livenessProbe:
      httpGet:
        path: /health
        port: 2379
        scheme: HTTP
      initialDelaySeconds: 15
      timeoutSeconds: 15
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 500m
        memory: 512Mi
  volumes:
  - name: etcd-data
    hostPath:
      path: /var/lib/etcd-static
      type: DirectoryOrCreate
  hostNetwork: true
  restartPolicy: Always
